---
title: "catdog_data_plotting_v1"
author: "Stephanie Huang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# SETUP

### Load in Packages

```{r}
library(readr) # read_csv
library(dplyr) #data wrangling
library(ggplot2) #graphs
library(stringr) # str_detect
library(RColorBrewer) #scale_fill_brewer
```


### Read in the data
```{r}
#Set working directory to source file location 
catdog <- read_csv("cleaned_catdog_data_v1.csv")

```


### Animals with your name?
```{r}
#By specific cases
my_name <- catdog %>%
  filter(name %in% c("Stephanie", "Steph", "Stephy",
                     "Stephie", "Stefanie"))

#Starting with
my_name_2 <- catdog %>%
  filter(str_detect(name, "^Steph|^Stef"))

```


### Cat as cat Dog as dog
```{r}
catascat <- filter(catdog, breed == "Cat")
dogasdog <- filter(catdog, breed == "Dog")

```


## Top cat & dog names
### Names sorted by type
```{r}
nm_x_typ <- catdog %>%
  group_by(type) %>%
  count(name, sort = TRUE) %>%
  slice_max(n, n = 10)

# #just to look at the silly uncommon names (2 pac the cat)
# bot_nm_x_type <- catdog %>%
#   group_by(type) %>%
#   count(name, sort = TRUE) %>%
#   filter(n <= 2)

```

### Make the bar plot
```{r}
bar_plot <- nm_x_typ %>%
  filter(type == "Cat") %>%
  ggplot(aes(x = reorder(name, n),
             y = n,
             fill = reorder(name, n)))

my_bar_plot <- bar_plot +
  geom_col(color = "grey10", alpha = 0.7) +
  labs(x = "Name", y = "Number of Cats",
       title = "Top 10 Cat Names") +
  scale_fill_brewer(palette = "Spectral") +
  coord_flip() +
  theme_classic()

plot(my_bar_plot)
```


### Boxplots for animal age (cat vs dog)
#### 
https://ggplot2.tidyverse.org/reference/ggtheme.html
https://personal.sron.nl/~pault/
```{r}
# Kinda ugly:( has overplotted points even if filter by suburb
#Orange - "#ffc99d"
#display.brewer.all()

box_plot <- catdog %>%
  filter(region == "Sunshine Coast" & suburb == "Pelican Waters") %>%
  ggplot(aes(x = type, y = age, fill = type))

my_box_plot <- box_plot +
  geom_boxplot(aes(fill = type), color = "grey10", alpha = 0.8, fatten = 1,
               size = 0.5, width = 0.25, outlier.shape = NA,
               position = position_dodge(width=0.7)) +
  stat_summary(fun=mean, geom ="point", shape = 4,
               size = 2, stroke = 0.5, color = "grey10",
               position = position_dodge(width=0.7)) +
  geom_point(color = "grey20", size = 1, shape = 1, alpha = 0.3,
             position=position_jitterdodge(
               dodge.width = 0.5, jitter.width = 0.25, jitter.height = 0.3)) +
  scale_y_continuous(breaks=seq(0, 25, 5)) + # seq(lower, upper, divisions)
  scale_x_discrete(labels=c("Meow", "Woof")) + #re-label x axis
  scale_fill_manual(name = "Animal Type", #Legend Title
                    values=alpha(c("#d6604d", "#4393c3", 0.9)),
                    breaks=c("Cat", "Dog"), #in dataframe
                    labels=c("Kitties", "Doggies"), #displayed
                    guide = guide_legend(title.position = "top")) +
   labs(y = 'Age (years)', x = 'Animal Type', 
       title = 'The Age of Cats & Dogs',
       subtitle ='in Pelican Waters, Sunshine Coast, Queensland, Australia' ) + #sets axis names & titles
  theme_bw()


plot(my_box_plot)

```

### Extras
#### histogram + facet_wrap
http://www.sthda.com/english/wiki/ggplot2-histogram-plot-quick-start-guide-r-software-and-data-visualization
```{r}
histo <- catdog %>%
  filter(region == "Sunshine Coast") %>%
  ggplot(aes(x = age, fill = type))

my_histo <- histo +
  geom_histogram(binwidth=1,
                 color = "grey10", alpha = 0.7) +
  facet_wrap(~type, ncol = 1, scales = "free") +
  scale_fill_manual(values=c("#c2a5cf", "#fdb366"))

plot(my_histo)
```

#### Pie graph (base R pie)
<https://www.learnbyexample.org/r-pie-chart-base-graph/>
```{r}

brd_x_typ <- catdog %>%
  group_by(type) %>%
  summarize(breeds = n_distinct(breed)) %>%
  mutate(pct = breeds/sum(breeds) * 100)

#round down to 2 
brd_x_typ$pct <- signif(brd_x_typ$pct, 2)

percent2plot <- paste(brd_x_typ$type, brd_x_typ$pct, "%")

#pie chart
pie(brd_x_typ$breeds, labels = percent2plot,
    col = c("lightpink", "lightblue"),
    main = "Percentage of unique breeds across animal type")

```

#### Pie graph 2 (ggplot)
```{r}
pcb <- catdog %>% 
  filter(type == "Cat") %>%
  count(breed, sort = TRUE) %>%
  slice_max(n, n = 15) %>%
  ggplot(aes(x = "", y = n, fill = breed))

p_pcb <- pcb +
  geom_col(color = "grey10", alpha = 0.6) +
  # geom_label(aes(label = n),
  #            position = position_stack(vjust = 0.5),
  #            show.legend = FALSE) +
  coord_polar(theta = "y") +
  theme_classic()
  
plot(p_pcb)
```
